switch to pnpm

diff --git a/.husky/pre-push b/.husky/pre-push
--- a/.husky/pre-push
+++ b/.husky/pre-push
@@ -1,21 +1,21 @@
   # 1. Force Prettier Structure
   echo "🐶 Husky: 🌊 Enforcing TypeScript Types Check ..."
-  yarn type-check || { echo "🐶 Husky: ❌ Enforcing Types Check. Aborting push."; exit 1; }
+  pnpm type-check || { echo "🐶 Husky: ❌ Enforcing Types Check. Aborting push."; exit 1; }
   echo "🐶 Husky: 🎉 TypeScript found no rule violations ..."
 
   # 2. Linting
   echo "🐶 Husky: 👮‍♂️ Executing EsLint ..."
-  yarn lint:eslint || { echo "🐶 Husky: ❌ ESLint found issues. Aborting push."; exit 1; }
+  pnpm lint:eslint || { echo "🐶 Husky: ❌ ESLint found issues. Aborting push."; exit 1; }
   echo "🐶 Husky: 🎉 Linter found no rule violations ..."
 
   # 3. Linting
   echo "🐶 Husky: 👮‍♂️ Executing Oxlint ..."
-  yarn lint:oxlint || { echo "🐶 Husky: ❌ Oxlint found issues. Aborting push."; exit 1; }
+  pnpm lint:oxlint || { echo "🐶 Husky: ❌ Oxlint found issues. Aborting push."; exit 1; }
   echo "🐶 Husky: 🎉 Oxlinter found no rule violations ..."
 
   # 4. Unit-Testing
   echo "🐶 Husky: 🧪 Executing test:coverage ..."
-  yarn test:coverage || { echo "🐶 Husky: ❌ Tests failed. Aborting push."; exit 1; }
+  pnpm test:coverage || { echo "🐶 Husky: ❌ Tests failed. Aborting push."; exit 1; }
   echo "🐶 Husky: 🎉 All tests passed successfully!"
 
   # 6. Success
